add_requires("spdlog 1.15.*")
-- add_requires("glad")
add_requires("glfw 3.4")

target("vi")
    set_kind("static")
    add_files("src/**.cpp")
    add_headerfiles("src/**.hpp")
    add_includedirs("src/", {public = true})
    add_includedirs("thirdparty/glad/include", {public = true})
    add_packages("spdlog", {public = true})
    -- add_packages("glad", {public = true})
    add_packages("glfw", {public = true})